### ISSUE TITLE
Constants should be the very first in your program

### ISSUE THREAD

**Issue by mayisa87** [asharif123/hangman#1]
https://github.com/asharif123/hangman/blob/f32137c457cc7adae396c3681d64595084b0cda3/Program.cs#L27-L28

Move your constants at the very beginning, it makes it easier to read the code and find the constants :)

https://github.com/asharif123/hangman/blob/f32137c457cc7adae396c3681d64595084b0cda3/Program.cs#L42

After the constants you should place the Random declaration, as this is something that is used globally too.

**Comment by asharif123** [comment]
fixed issue #1 by moving constants to very beginning of program
