### ISSUE TITLE
Use ReadKey to read single characters from console

### ISSUE THREAD

**Issue by mayisa87** [asharif123/hangman#2]
https://github.com/asharif123/hangman/blob/f32137c457cc7adae396c3681d64595084b0cda3/Program.cs#L56

In case that you need a single character to be read from Console, you can use the ReadKey method to do so. 
It will return you a char only.

It will look like 
`char myChar = Console.ReadKey().KeyChar;`

Here the link to the documentation: https://learn.microsoft.com/en-us/dotnet/api/system.console.readkey?view=net-7.0

**Comment by asharif123** [comment]
fixed issue #2 by reading single characters from console
