### ISSUE TITLE
No need for +1

### ISSUE THREAD

**Issue by mayisa87** [asharif123/hangman#3]
https://github.com/asharif123/hangman/blob/1acdd78b65a22381f4ca24b418bb18d94333c5a9/Program.cs#L33

The random Next method does not include the upper bound, so if you want to have values between 1 and 10 you need to call it like:
rng.Next(1,10+1);

If your list has 10 items in it, and you want to have the position of one of them, you need an index between 0 and 9. The hangmanWords.Count will already give you the value 10, so no need to use the +1

**Comment by asharif123** [comment]
fixed issue #3 no need for +1
