### ISSUE TITLE
Directly create an char[]

### ISSUE THREAD

**Issue by mayisa87** [asharif123/hangman#4]
https://github.com/asharif123/hangman/blob/1acdd78b65a22381f4ca24b418bb18d94333c5a9/Program.cs#L50-L60

And instead of first creating the string hiddenWord, filling it with _ and then creating an array out of the string, you could create an array with the rigth size from beginning and fill the array with values directly.

char myArray = new char[length];

To fill it right, you can use a for loop, like you already did in the last exercise? Having a while loop for this purpose, is not the best choice

**Comment by asharif123** [comment]
fixed issue #4 by directly creating char[]
