### ISSUE TITLE
No need to store the chosen word as array

### ISSUE THREAD

**Issue by mayisa87** [asharif123/hangman#5]
https://github.com/asharif123/hangman/blob/1acdd78b65a22381f4ca24b418bb18d94333c5a9/Program.cs#L48

It's a good way, that you choose to have an array, storing the hidden letters 💪🏻👍🏻

But it is not necessary to store an additional array for your chosen word. You can loop through a string and all it's characters like through an array. As you don't need to modify the chosenWord, you only need to loop through it, and access values, it is enough to have a string, no array

**Comment by asharif123** [comment]
fixed issue #5 by getting rid of array for chosen word
