### ISSUE TITLE
Only first occurance is replaced 

### ISSUE THREAD

**Issue by mayisa87** [asharif123/hangman#6]
https://github.com/asharif123/hangman/blob/1acdd78b65a22381f4ca24b418bb18d94333c5a9/Program.cs#L76-L86

Currently you are looping with an for each loop through your chosen word and check if the character matches the entered one. 

![image](https://github.com/asharif123/hangman/assets/130921606/5a4f5eae-3b74-4aee-a9d5-497f24ed1764)

Why it doesn't work, shows the screen shot. Your if condition will find an occurance, but the "indexOf" method does always return you the position of the first occurance in word. 

So the better option:
Loop through your chosenWord character by character, with an for loop. This will give you the possibility to access the single characters of your chosenWord by index (like you already learned in last exercise) and compare this character then against the entered one from user.

If you have a match, you can replace the "_" in your lettersOfHiddenWord array, again, by using the index of your for loop.

**Comment by asharif123** [comment]
fixed issue #6 only first occurrence is replaced issue
